# Generated by Django 5.0.6 on 2026-07-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="id_area",
            field=models.ForeignKey(
                blank=True,
                db_column="id_area",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="usuarios",
                to="core.area",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="id_rol",
            field=models.ForeignKey(
                db_column="id_rol",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="usuarios",
                to="accounts.rol",
            ),
        ),
    ]
