# Generated by Django 5.0.6 on 2026-07-21 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponenteMaquina",
            fields=[
                ("id_componente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_componente", models.CharField(max_length=100)),
                (
                    "tipo_componente",
                    models.CharField(
                        choices=[
                            ("MECANICO", "Mecánico"),
                            ("ELECTRICO", "Eléctrico"),
                            ("ELECTRONICO", "Electrónico"),
                            ("TERMICO", "Térmico"),
                            ("NEUMATICO", "Neumático"),
                            ("REFRIGERACION", "Refrigeración"),
                            ("SANITARIO", "Sanitario"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "vida_util_estimada_horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "criticidad_componente",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("MUY_ALTA", "Muy alta"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                ("requiere_lubricacion", models.BooleanField(default=False)),
                ("requiere_calibracion", models.BooleanField(default=False)),
                (
                    "estado_componente",
                    models.CharField(
                        choices=[
                            ("BUENO", "Bueno"),
                            ("OBSERVADO", "Observado"),
                            ("DANADO", "Dañado"),
                            ("CAMBIADO", "Cambiado"),
                            ("FUERA_DE_SERVICIO", "Fuera de servicio"),
                        ],
                        default="BUENO",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Componente",
                "verbose_name_plural": "Componentes",
                "db_table": "componentes_maquina",
                "ordering": ["nombre_componente"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FuncionProceso",
            fields=[
                ("id_funcion", models.AutoField(primary_key=True, serialize=False)),
                ("numero_etapa", models.IntegerField()),
                ("nombre_etapa", models.CharField(max_length=100)),
                ("funcion_principal", models.TextField()),
                (
                    "criticidad_funcion",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("MUY_ALTA", "Muy alta"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("INACTIVA", "Inactiva")],
                        default="ACTIVA",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Función de proceso",
                "verbose_name_plural": "Funciones de proceso",
                "db_table": "funciones_proceso",
                "ordering": ["numero_etapa"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoMaquina",
            fields=[
                ("id_historial", models.AutoField(primary_key=True, serialize=False)),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPERATIVA", "Operativa"),
                            ("OBSERVADA", "Observada"),
                            ("PARADA", "Parada"),
                            ("MANTENIMIENTO_PREVENTIVO", "Mantenimiento preventivo"),
                            ("MANTENIMIENTO_CORRECTIVO", "Mantenimiento correctivo"),
                            ("FUERA_DE_SERVICIO", "Fuera de servicio"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("OPERATIVA", "Operativa"),
                            ("OBSERVADA", "Observada"),
                            ("PARADA", "Parada"),
                            ("MANTENIMIENTO_PREVENTIVO", "Mantenimiento preventivo"),
                            ("MANTENIMIENTO_CORRECTIVO", "Mantenimiento correctivo"),
                            ("FUERA_DE_SERVICIO", "Fuera de servicio"),
                        ],
                        max_length=30,
                    ),
                ),
                ("motivo_cambio", models.TextField(blank=True, null=True)),
                ("fecha_hora_cambio", models.DateTimeField(auto_now_add=True)),
                ("observacion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Historial de estado",
                "verbose_name_plural": "Historial de estados",
                "db_table": "historial_estado_maquina",
                "ordering": ["-fecha_hora_cambio"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Maquina",
            fields=[
                ("id_maquina", models.AutoField(primary_key=True, serialize=False)),
                ("codigo_activo", models.CharField(max_length=30, unique=True)),
                ("nombre_maquina", models.CharField(max_length=150)),
                ("tipo_maquina", models.CharField(max_length=100)),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                ("modelo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "numero_serie",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "capacidad_valor",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "capacidad_unidad",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "tipo_energia",
                    models.CharField(
                        choices=[
                            ("ELECTRICA", "Eléctrica"),
                            ("GLP", "GLP"),
                            ("NEUMATICA", "Neumática"),
                            ("MIXTA", "Mixta"),
                            ("BATERIA", "Batería"),
                            ("NO_APLICA", "No aplica"),
                        ],
                        default="ELECTRICA",
                        max_length=20,
                    ),
                ),
                (
                    "potencia_kw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "potencia_hp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "consumo_estimado_hora",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "consumo_estimado_lote",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "criticidad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("MUY_ALTA", "Muy alta"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "estado_operativo",
                    models.CharField(
                        choices=[
                            ("OPERATIVA", "Operativa"),
                            ("OBSERVADA", "Observada"),
                            ("PARADA", "Parada"),
                            ("MANTENIMIENTO_PREVENTIVO", "Mantenimiento preventivo"),
                            ("MANTENIMIENTO_CORRECTIVO", "Mantenimiento correctivo"),
                            ("FUERA_DE_SERVICIO", "Fuera de servicio"),
                        ],
                        default="OPERATIVA",
                        max_length=30,
                    ),
                ),
                (
                    "ubicacion_fisica",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("fecha_instalacion", models.DateField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("requiere_checklist_diario", models.BooleanField(default=True)),
                ("requiere_calibracion", models.BooleanField(default=False)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Máquina",
                "verbose_name_plural": "Máquinas",
                "db_table": "maquinas",
                "ordering": ["codigo_activo"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MaquinaFuncion",
            fields=[
                (
                    "id_maquina_funcion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("es_funcion_principal", models.BooleanField(default=False)),
                ("observacion", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Máquina-Función",
                "verbose_name_plural": "Máquinas-Funciones",
                "db_table": "maquina_funcion",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id_area", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_area", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("INACTIVA", "Inactiva")],
                        default="ACTIVA",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "responsable_area",
                    models.ForeignKey(
                        blank=True,
                        db_column="responsable_area",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="areas_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "db_table": "areas",
                "ordering": ["nombre_area"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FallaProbable",
            fields=[
                (
                    "id_falla_probable",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descripcion_falla", models.TextField()),
                ("causa_probable", models.TextField(blank=True, null=True)),
                ("efecto_en_produccion", models.TextField(blank=True, null=True)),
                (
                    "probabilidad_porcentaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "nivel_probabilidad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("MUY_ALTA", "Muy alta"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                ("severidad", models.IntegerField(blank=True, null=True)),
                ("detectabilidad", models.IntegerField(blank=True, null=True)),
                (
                    "nivel_riesgo",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                        ],
                        default="MEDIO",
                        max_length=10,
                    ),
                ),
                ("accion_preventiva_sugerida", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVA", "Activa"), ("INACTIVA", "Inactiva")],
                        default="ACTIVA",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id_componente",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_componente",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="fallas_probables",
                        to="core.componentemaquina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Falla probable",
                "verbose_name_plural": "Fallas probables",
                "db_table": "fallas_probables",
                "managed": True,
            },
        ),
    ]
