# Generated by Django 5.0.6 on 2026-07-21 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("mantenimiento", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historialestadomaquina",
            name="id_ot",
            field=models.ForeignKey(
                blank=True,
                db_column="id_ot",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="historial_estados",
                to="mantenimiento.ordentrabajo",
            ),
        ),
        migrations.AddField(
            model_name="historialestadomaquina",
            name="id_usuario",
            field=models.ForeignKey(
                db_column="id_usuario",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="cambios_estado_maquina",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maquina",
            name="id_area",
            field=models.ForeignKey(
                db_column="id_area",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="maquinas",
                to="core.area",
            ),
        ),
        migrations.AddField(
            model_name="maquina",
            name="responsable_maquina",
            field=models.ForeignKey(
                blank=True,
                db_column="responsable_maquina",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="maquinas_responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialestadomaquina",
            name="id_maquina",
            field=models.ForeignKey(
                db_column="id_maquina",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="historial_estados",
                to="core.maquina",
            ),
        ),
        migrations.AddField(
            model_name="fallaprobable",
            name="id_maquina",
            field=models.ForeignKey(
                db_column="id_maquina",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="fallas_probables",
                to="core.maquina",
            ),
        ),
        migrations.AddField(
            model_name="componentemaquina",
            name="id_maquina",
            field=models.ForeignKey(
                db_column="id_maquina",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="componentes",
                to="core.maquina",
            ),
        ),
        migrations.AddField(
            model_name="maquinafuncion",
            name="id_funcion",
            field=models.ForeignKey(
                db_column="id_funcion",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="maquinas",
                to="core.funcionproceso",
            ),
        ),
        migrations.AddField(
            model_name="maquinafuncion",
            name="id_maquina",
            field=models.ForeignKey(
                db_column="id_maquina",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="funciones",
                to="core.maquina",
            ),
        ),
    ]
