# Generated by Django 5.0.6 on 2026-07-21 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteProduccion",
            fields=[
                ("id_lote", models.AutoField(primary_key=True, serialize=False)),
                ("codigo_lote", models.CharField(max_length=50, unique=True)),
                ("fecha_produccion", models.DateField()),
                ("producto", models.CharField(max_length=100)),
                (
                    "kg_cacao_ingresado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "kg_producto_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estado_lote",
                    models.CharField(
                        choices=[
                            ("PROGRAMADO", "Programado"),
                            ("EN_PROCESO", "En proceso"),
                            ("DETENIDO", "Detenido"),
                            ("FINALIZADO", "Finalizado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="PROGRAMADO",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "responsable_produccion",
                    models.ForeignKey(
                        blank=True,
                        db_column="responsable_produccion",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de producción",
                "verbose_name_plural": "Lotes de producción",
                "db_table": "lotes_produccion",
                "ordering": ["-fecha_produccion"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ConsumoEnergetico",
            fields=[
                ("id_consumo", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                (
                    "tipo_energia",
                    models.CharField(
                        choices=[
                            ("ELECTRICIDAD", "Electricidad"),
                            ("GLP", "GLP"),
                            ("NEUMATICA", "Neumática"),
                            ("MIXTA", "Mixta"),
                            ("BATERIA", "Batería"),
                            ("NO_APLICA", "No aplica"),
                        ],
                        default="ELECTRICIDAD",
                        max_length=15,
                    ),
                ),
                (
                    "potencia_kw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "horas_uso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "kwh_estimado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "glp_estimado_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costo_unitario_energia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "costo_total_energia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "id_maquina",
                    models.ForeignKey(
                        db_column="id_maquina",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="consumos",
                        to="core.maquina",
                    ),
                ),
                (
                    "id_lote",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_lote",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="consumos",
                        to="produccion.loteproduccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo energético",
                "verbose_name_plural": "Consumos energéticos",
                "db_table": "consumo_energetico",
                "ordering": ["-fecha"],
                "managed": True,
            },
        ),
    ]
