# Generated by Django 5.0.6 on 2026-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinaRepuesto',
            fields=[
                ('id_maquina_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_recomendada_stock', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('criticidad_repuesto', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('tiempo_reposicion_dias', models.IntegerField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Repuesto por máquina',
                'verbose_name_plural': 'Repuestos por máquina',
                'db_table': 'maquina_repuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoRepuesto',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste positivo'), ('AJUSTE_NEGATIVO', 'Ajuste negativo'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento de repuesto',
                'verbose_name_plural': 'Movimientos de repuestos',
                'db_table': 'movimiento_repuestos',
                'ordering': ['-fecha_movimiento'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=150)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tipo_proveedor', models.CharField(choices=[('REPUESTOS', 'Repuestos'), ('TALLER', 'Taller'), ('CALIBRACION', 'Calibración'), ('REFRIGERACION', 'Refrigeración'), ('ELECTRICO', 'Eléctrico'), ('MECANICO', 'Mecánico'), ('GAS', 'Gas'), ('OTRO', 'Otro')], default='OTRO', max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre_proveedor'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_repuesto', models.CharField(max_length=50, unique=True)),
                ('nombre_repuesto', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(default='UNIDAD', max_length=30)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('OBSOLETO', 'Obsoleto'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'db_table': 'repuestos',
                'ordering': ['nombre_repuesto'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicioExterno',
            fields=[
                ('id_servicio_externo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_envio', models.TextField()),
                ('fecha_salida', models.DateField()),
                ('fecha_retorno_estimada', models.DateField(blank=True, null=True)),
                ('fecha_retorno_real', models.DateField(blank=True, null=True)),
                ('costo_servicio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diagnostico_externo', models.TextField(blank=True, null=True)),
                ('estado_servicio', models.CharField(choices=[('ENVIADO', 'Enviado'), ('EN_REPARACION', 'En reparación'), ('RETORNADO', 'Retornado'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='ENVIADO', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio externo',
                'verbose_name_plural': 'Servicios externos',
                'db_table': 'servicios_externos',
                'ordering': ['-fecha_salida'],
                'managed': False,
            },
        ),
    ]
