# Generated by Django 5.0.6 on 2026-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id_adjunto', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_entidad', models.CharField(choices=[('MAQUINA', 'Máquina'), ('CHECKLIST', 'Checklist'), ('FALLA', 'Falla'), ('OT', 'Orden de trabajo'), ('REPUESTO', 'Repuesto'), ('SERVICIO_EXTERNO', 'Servicio externo'), ('REPORTE', 'Reporte'), ('OBSERVACION', 'Observación'), ('OTRO', 'Otro')], max_length=20)),
                ('id_entidad', models.IntegerField()),
                ('categoria_archivo', models.CharField(choices=[('FOTO_MAQUINA', 'Foto de máquina'), ('PLACA_TECNICA', 'Placa técnica'), ('FICHA_TECNICA', 'Ficha técnica'), ('MANUAL', 'Manual'), ('EVIDENCIA', 'Evidencia'), ('PDF', 'PDF'), ('INFORME', 'Informe'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('nombre_archivo', models.CharField(max_length=200)),
                ('tipo_archivo', models.CharField(choices=[('JPG', 'JPG'), ('JPEG', 'JPEG'), ('PNG', 'PNG'), ('PDF', 'PDF'), ('DOCX', 'DOCX'), ('XLSX', 'XLSX'), ('CSV', 'CSV'), ('TXT', 'TXT'), ('OTRO', 'Otro')], default='OTRO', max_length=10)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('descargable', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', max_length=10)),
            ],
            options={
                'verbose_name': 'Archivo adjunto',
                'verbose_name_plural': 'Archivos adjuntos',
                'db_table': 'archivos_adjuntos',
                'ordering': ['-fecha_subida'],
                'managed': False,
            },
        ),
    ]
