# Generated by Django 5.0.6 on 2026-06-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id_auditoria', models.AutoField(primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('id_registro_afectado', models.IntegerField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('DESCARGAR', 'Descargar'), ('GENERAR_REPORTE', 'Generar reporte'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditoría del sistema',
                'db_table': 'auditoria_sistema',
                'ordering': ['-fecha_hora'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleReporteGenerado',
            fields=[
                ('id_detalle_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_registro', models.CharField(choices=[('CHECKLIST', 'Checklist'), ('OBSERVACION', 'Observación'), ('FALLA', 'Falla'), ('OT', 'Orden de trabajo'), ('CONSUMO', 'Consumo'), ('REPUESTO', 'Repuesto'), ('MAQUINA', 'Máquina'), ('INDICADOR', 'Indicador'), ('OTRO', 'Otro')], max_length=15)),
                ('id_registro', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detalle de reporte generado',
                'verbose_name_plural': 'Detalles de reportes generados',
                'db_table': 'detalle_reportes_generados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndicadorMantenimiento',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('horas_programadas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('horas_parada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponibilidad_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('numero_fallas', models.IntegerField(default=0)),
                ('mtbf_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mttr_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cumplimiento_preventivo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumo_energia_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicador de mantenimiento',
                'verbose_name_plural': 'Indicadores de mantenimiento',
                'db_table': 'indicadores_mantenimiento',
                'ordering': ['-periodo_fin'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id_reporte_generado', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_reporte', models.CharField(max_length=50, unique=True)),
                ('tipo_reporte', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('POR_MAQUINA', 'Por máquina'), ('POR_AREA', 'Por área'), ('POR_OT', 'Por OT'), ('PERSONALIZADO', 'Personalizado')], default='SEMANAL', max_length=15)),
                ('titulo_reporte', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10)),
                ('ruta_archivo', models.CharField(max_length=255)),
                ('descargable', models.BooleanField(default=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado'), ('DESCARGADO', 'Descargado'), ('ANULADO', 'Anulado')], default='GENERADO', max_length=15)),
            ],
            options={
                'verbose_name': 'Reporte generado',
                'verbose_name_plural': 'Reportes generados',
                'db_table': 'reportes_generados',
                'ordering': ['-fecha_generacion'],
                'managed': False,
            },
        ),
    ]
