# Generated by Django 5.0.6 on 2026-07-21 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("produccion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistEjecucion",
            fields=[
                ("id_checklist", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MANANA", "Mañana"),
                            ("TARDE", "Tarde"),
                            ("NOCHE", "Noche"),
                            ("UNICO", "Único"),
                        ],
                        default="MANANA",
                        max_length=10,
                    ),
                ),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                (
                    "resultado_general",
                    models.CharField(
                        choices=[
                            ("APTA", "Apta"),
                            ("OBSERVADA", "Observada"),
                            ("NO_APTA", "No apta"),
                        ],
                        default="APTA",
                        max_length=10,
                    ),
                ),
                ("permite_produccion", models.BooleanField(default=True)),
                ("observacion_general", models.TextField(blank=True, null=True)),
                (
                    "firma_responsable",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("genero_reporte_falla", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id_maquina",
                    models.ForeignKey(
                        db_column="id_maquina",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="checklists",
                        to="core.maquina",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejecución de checklist",
                "verbose_name_plural": "Ejecuciones de checklist",
                "db_table": "checklist_ejecucion",
                "ordering": ["-fecha", "-creado_en"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ChecklistPlantilla",
            fields=[
                (
                    "id_item_checklist",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("pregunta", models.TextField()),
                (
                    "tipo_respuesta",
                    models.CharField(
                        choices=[
                            ("SI_NO", "Sí / No"),
                            ("TEXTO", "Texto"),
                            ("NUMERO", "Número"),
                            ("TEMPERATURA", "Temperatura"),
                            ("OBSERVACION", "Observación"),
                        ],
                        default="SI_NO",
                        max_length=15,
                    ),
                ),
                (
                    "valor_minimo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valor_maximo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("obligatorio", models.BooleanField(default=True)),
                ("bloquea_produccion", models.BooleanField(default=False)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Diario"),
                            ("SEMANAL", "Semanal"),
                            ("MENSUAL", "Mensual"),
                            ("POR_LOTE", "Por lote"),
                        ],
                        default="DIARIO",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("INACTIVO", "Inactivo")],
                        default="ACTIVO",
                        max_length=10,
                    ),
                ),
                ("orden_visualizacion", models.IntegerField(default=1)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id_maquina",
                    models.ForeignKey(
                        db_column="id_maquina",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="items_checklist",
                        to="core.maquina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem de checklist",
                "verbose_name_plural": "Plantilla de checklist",
                "db_table": "checklist_plantilla",
                "ordering": ["id_maquina", "orden_visualizacion"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ChecklistDetalle",
            fields=[
                (
                    "id_checklist_detalle",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("respuesta", models.TextField(blank=True, null=True)),
                (
                    "valor_medido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("cumple", models.BooleanField(default=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                ("requiere_ot", models.BooleanField(default=False)),
                (
                    "nivel_alerta",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                        ],
                        default="BAJO",
                        max_length=10,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "id_checklist",
                    models.ForeignKey(
                        db_column="id_checklist",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="detalles",
                        to="mantenimiento.checklistejecucion",
                    ),
                ),
                (
                    "id_item_checklist",
                    models.ForeignKey(
                        db_column="id_item_checklist",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="detalles",
                        to="mantenimiento.checklistplantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de checklist",
                "verbose_name_plural": "Detalles de checklist",
                "db_table": "checklist_detalle",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MedicionOperativa",
            fields=[
                ("id_medicion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "vibracion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ruido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amperaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "presion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "velocidad",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "id_lote",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_lote",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mediciones",
                        to="produccion.loteproduccion",
                    ),
                ),
                (
                    "id_maquina",
                    models.ForeignKey(
                        db_column="id_maquina",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mediciones",
                        to="core.maquina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medición operativa",
                "verbose_name_plural": "Mediciones operativas",
                "db_table": "mediciones_operativas",
                "ordering": ["-fecha_hora"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ObservacionDiaria",
            fields=[
                ("id_observacion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MANANA", "Mañana"),
                            ("TARDE", "Tarde"),
                            ("NOCHE", "Noche"),
                            ("UNICO", "Único"),
                        ],
                        default="MANANA",
                        max_length=10,
                    ),
                ),
                (
                    "tipo_observacion",
                    models.CharField(
                        choices=[
                            ("RUIDO", "Ruido"),
                            ("VIBRACION", "Vibración"),
                            ("TEMPERATURA", "Temperatura"),
                            ("FUGA", "Fuga"),
                            ("LIMPIEZA", "Limpieza"),
                            ("ENERGIA", "Energía"),
                            ("FALLA", "Falla"),
                            ("CALIDAD", "Calidad"),
                            ("SEGURIDAD", "Seguridad"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=15,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "nivel_importancia",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                        ],
                        default="BAJO",
                        max_length=10,
                    ),
                ),
                ("afecta_produccion", models.BooleanField(default=False)),
                ("requiere_revision_tecnica", models.BooleanField(default=False)),
                (
                    "estado_observacion",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("REVISADA", "Revisada"),
                            ("CONVERTIDA_A_OT", "Convertida a OT"),
                            ("CERRADA", "Cerrada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id_lote",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_lote",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="observaciones_diarias",
                        to="produccion.loteproduccion",
                    ),
                ),
                (
                    "id_maquina",
                    models.ForeignKey(
                        db_column="id_maquina",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="observaciones_diarias",
                        to="core.maquina",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="observaciones_diarias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Observación diaria",
                "verbose_name_plural": "Observaciones diarias",
                "db_table": "observaciones_diarias",
                "ordering": ["-fecha_hora"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OrdenTrabajo",
            fields=[
                ("id_ot", models.AutoField(primary_key=True, serialize=False)),
                ("codigo_ot", models.CharField(max_length=30, unique=True)),
                (
                    "tipo_ot",
                    models.CharField(
                        choices=[
                            ("PREVENTIVA", "Preventiva"),
                            ("CORRECTIVA", "Correctiva"),
                            ("PREDICTIVA", "Predictiva"),
                            ("CALIBRACION", "Calibración"),
                            ("INSPECCION", "Inspección"),
                        ],
                        default="PREVENTIVA",
                        max_length=15,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "estado_ot",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PROGRAMADA", "Programada"),
                            ("EN_EJECUCION", "En ejecución"),
                            ("CERRADA", "Cerrada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("descripcion_trabajo", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_programada", models.DateField(blank=True, null=True)),
                ("hora_programada", models.TimeField(blank=True, null=True)),
                ("fecha_inicio_real", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin_real", models.DateTimeField(blank=True, null=True)),
                (
                    "tiempo_parada_horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("requiere_repuesto", models.BooleanField(default=False)),
                ("requiere_servicio_externo", models.BooleanField(default=False)),
                (
                    "tipo_atencion",
                    models.CharField(
                        choices=[
                            ("EN_PLANTA", "En planta"),
                            ("CAMBIO_PIEZA", "Cambio de pieza"),
                            ("TALLER_EXTERNO", "Taller externo"),
                            ("MAQUINA_ALTERNATIVA", "Máquina alternativa"),
                            ("PENDIENTE_DEFINIR", "Pendiente definir"),
                        ],
                        default="PENDIENTE_DEFINIR",
                        max_length=20,
                    ),
                ),
                (
                    "costo_mano_obra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_repuestos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_servicio_externo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "costo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observacion_cierre", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id_maquina",
                    models.ForeignKey(
                        db_column="id_maquina",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ordenes",
                        to="core.maquina",
                    ),
                ),
                (
                    "responsable_tecnico",
                    models.ForeignKey(
                        blank=True,
                        db_column="responsable_tecnico",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ordenes_tecnico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        db_column="validado_por",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="ordenes_validadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de trabajo",
                "verbose_name_plural": "Órdenes de trabajo",
                "db_table": "ordenes_trabajo",
                "ordering": ["-fecha_creacion"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenTrabajo",
            fields=[
                ("id_detalle_ot", models.AutoField(primary_key=True, serialize=False)),
                ("actividad_realizada", models.TextField()),
                ("diagnostico", models.TextField(blank=True, null=True)),
                ("causa_raiz", models.TextField(blank=True, null=True)),
                ("accion_correctiva", models.TextField(blank=True, null=True)),
                (
                    "resultado_prueba",
                    models.CharField(
                        choices=[
                            ("APROBADO", "Aprobado"),
                            ("OBSERVADO", "Observado"),
                            ("NO_APROBADO", "No aprobado"),
                            ("NO_APLICA", "No aplica"),
                        ],
                        default="NO_APLICA",
                        max_length=15,
                    ),
                ),
                (
                    "tiempo_ejecucion_horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "id_ot",
                    models.ForeignKey(
                        db_column="id_ot",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="detalles",
                        to="mantenimiento.ordentrabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de OT",
                "verbose_name_plural": "Detalles de OT",
                "db_table": "detalle_orden_trabajo",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PlanMantenimiento",
            fields=[
                ("id_plan", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tipo_mantenimiento",
                    models.CharField(
                        choices=[
                            ("PREVENTIVO", "Preventivo"),
                            ("PREDICTIVO", "Predictivo"),
                            ("CALIBRACION", "Calibración"),
                            ("LIMPIEZA_PROFUNDA", "Limpieza profunda"),
                            ("INSPECCION", "Inspección"),
                        ],
                        default="PREVENTIVO",
                        max_length=20,
                    ),
                ),
                ("actividad", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("DIARIO", "Diario"),
                            ("SEMANAL", "Semanal"),
                            ("MENSUAL", "Mensual"),
                            ("TRIMESTRAL", "Trimestral"),
                            ("SEMESTRAL", "Semestral"),
                            ("ANUAL", "Anual"),
                            ("POR_HORAS_USO", "Por horas de uso"),
                        ],
                        default="SEMANAL",
                        max_length=15,
                    ),
                ),
                (
                    "cada_horas_uso",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "duracion_estimada_horas",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("requiere_parada", models.BooleanField(default=True)),
                (
                    "horario_recomendado",
                    models.CharField(
                        choices=[
                            ("ANTES_PRODUCCION", "Antes de producción"),
                            ("FIN_JORNADA", "Fin de jornada"),
                            ("FIN_SEMANA", "Fin de semana"),
                            ("FUERA_TURNO", "Fuera de turno"),
                            ("DIA_PARCIAL", "Día parcial"),
                            ("CUANDO_APLIQUE", "Cuando aplique"),
                        ],
                        default="FIN_JORNADA",
                        max_length=20,
                    ),
                ),
                ("fecha_ultima_ejecucion", models.DateField(blank=True, null=True)),
                ("fecha_proxima_ejecucion", models.DateField(blank=True, null=True)),
                (
                    "estado_plan",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("VENCIDO", "Vencido"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="ACTIVO",
                        max_length=15,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id_maquina",
                    models.ForeignKey(
                        db_column="id_maquina",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="planes",
                        to="core.maquina",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        db_column="responsable",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="planes_responsable",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de mantenimiento",
                "verbose_name_plural": "Planes de mantenimiento",
                "db_table": "plan_mantenimiento",
                "ordering": ["fecha_proxima_ejecucion"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="ordentrabajo",
            name="id_plan",
            field=models.ForeignKey(
                blank=True,
                db_column="id_plan",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordenes",
                to="mantenimiento.planmantenimiento",
            ),
        ),
        migrations.CreateModel(
            name="ReporteFalla",
            fields=[
                (
                    "id_reporte_falla",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("codigo_reporte", models.CharField(max_length=30, unique=True)),
                ("fecha_reporte", models.DateTimeField(auto_now_add=True)),
                (
                    "turno",
                    models.CharField(
                        choices=[
                            ("MANANA", "Mañana"),
                            ("TARDE", "Tarde"),
                            ("NOCHE", "Noche"),
                            ("UNICO", "Único"),
                        ],
                        default="MANANA",
                        max_length=10,
                    ),
                ),
                ("sintoma", models.CharField(max_length=150)),
                ("descripcion_falla", models.TextField()),
                (
                    "nivel_urgencia",
                    models.CharField(
                        choices=[
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                        ],
                        default="MEDIO",
                        max_length=10,
                    ),
                ),
                ("afecta_produccion", models.BooleanField(default=False)),
                (
                    "origen_reporte",
                    models.CharField(
                        choices=[
                            ("CHECKLIST", "Checklist"),
                            ("OBSERVACION_DIARIA", "Observación diaria"),
                            ("PRODUCCION", "Producción"),
                            ("MANTENIMIENTO", "Mantenimiento"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                (
                    "estado_reporte",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("EN_REVISION", "En revisión"),
                            ("CONVERTIDO_A_OT", "Convertido a OT"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="ABIERTO",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "id_lote",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_lote",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reportes_falla",
                        to="produccion.loteproduccion",
                    ),
                ),
                (
                    "id_maquina",
                    models.ForeignKey(
                        db_column="id_maquina",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reportes_falla",
                        to="core.maquina",
                    ),
                ),
                (
                    "id_usuario_reporta",
                    models.ForeignKey(
                        db_column="id_usuario_reporta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="reportes_falla",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de falla",
                "verbose_name_plural": "Reportes de falla",
                "db_table": "reportes_falla",
                "ordering": ["-fecha_reporte"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="ordentrabajo",
            name="id_reporte_falla",
            field=models.ForeignKey(
                blank=True,
                db_column="id_reporte_falla",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ordenes",
                to="mantenimiento.reportefalla",
            ),
        ),
    ]
